# Generated by Django 4.2.3 on 2023-07-31 22:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Apps', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='responsables',
            new_name='adopcion',
        ),
        migrations.RenameModel(
            old_name='adoptantes',
            new_name='adoptar',
        ),
    ]
